In [1]:
import pandas as pd
import plotnine as p9
import numpy as np
import os

In [2]:
PLOT_DIR = 'data/general_plots'
os.makedirs(PLOT_DIR, exist_ok=True)

In [3]:
pdmorl_file = 'data/pdmorl_stats.csv'
pcpl_file = 'data/pcpl_stats.csv'
envelope_file = 'data/envelope_stats.csv'

In [4]:
pdmorl = pd.read_csv(pdmorl_file)
pdmorl

,problem,config,checkpoint,hypervolume,normalized_hv,percent_non_dominated,ordering_score,pref_grid_step,tau,learning_rate,gamma,batch_size,seed,timestamp
0,problem_0,problem_0.yml,NaN,416.329032,0.928839,0.615385,0.984510,0.05,0.001,0.0006,0.95,256,1,2026-05-14T19:02:18
1,problem_0,problem_0.yml,NaN,444.785398,0.992326,1.000000,1.000000,0.05,0.001,0.0006,0.95,256,2,2026-05-14T19:02:22
2,problem_0,problem_0.yml,NaN,409.849468,0.914383,0.769231,1.000000,0.05,0.001,0.0006,0.95,256,3,2026-05-14T19:02:22
3,problem_0,problem_0.yml,NaN,433.753306,0.967713,0.692308,0.987578,0.05,0.001,0.0006,0.95,256,0,2026-05-14T19:02:25
4,problem_0,problem_0.yml,NaN,437.596712,0.976288,1.000000,0.993056,0.05,0.001,0.0006,0.95,256,4,2026-05-14T19:52:11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,problem_5e,problem_5e.yml,NaN,278514.771839,0.613366,0.180220,0.516654,0.05,0.001,0.0001,0.99,128,0,2026-05-15T12:59:06
76,problem_5e,problem_5e.yml,NaN,145011.704661,0.319355,0.112088,0.706337,0.05,0.001,0.0001,0.99,128,1,2026-05-15T13:00:20
77,problem_5e,problem_5e.yml,NaN,132228.709406,0.291204,0.120330,0.391170,0.05,0.001,0.0001,0.99,128,2,2026-05-15T13:23:17
78,problem_5e,problem_5e.yml,NaN,138930.662521,0.305963,0.112088,0.647051,0.05,0.001,0.0001,0.99,128,3,2026-05-15T13:36:30
79,problem_5e,problem_5e.yml,NaN,278432.885190,0.613185,0.174176,0.578394,0.05,0.001,0.0001,0.99,128,4,2026-05-15T13:50:31

In [5]:
pcpl = pd.read_csv(pcpl_file)
pcpl

,env_name,hypervolume,normalized_hv,non_dominated,ordering,architecture_idx,clip_range,entropy,lr,n_epochs,n_steps,scalarization_method,seed,smoothness,target_kl,sweep_timesteps,wandb_run_name
0,problem_0,440.922607,0.983708,1.000000,1.000000,0,0.226605,0.005462,0.000053,20,2048,smooth_tchebycheff,1,0.019041,0.013451,200000,morning-sweep-28
1,problem_0,448.225042,1.000000,1.000000,1.000000,0,0.226605,0.005462,0.000053,20,2048,smooth_tchebycheff,2,0.019041,0.013451,200000,morning-sweep-28
2,problem_0,448.225042,1.000000,1.000000,1.000000,0,0.226605,0.005462,0.000053,20,2048,smooth_tchebycheff,3,0.019041,0.013451,200000,morning-sweep-28
3,problem_0,448.225042,1.000000,1.000000,1.000000,0,0.226605,0.005462,0.000053,20,2048,smooth_tchebycheff,4,0.019041,0.013451,200000,morning-sweep-28
4,problem_0,448.225042,1.000000,1.000000,1.000000,0,0.226605,0.005462,0.000053,20,2048,smooth_tchebycheff,0,0.019041,0.013451,200000,morning-sweep-28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,problem_5e,342527.817214,0.754340,0.218681,0.762760,0,0.192599,0.062361,0.000099,20,2048,smooth_tchebycheff,0,0.064093,0.016039,200000,dazzling-sweep-24
76,problem_5e,338847.369605,0.746235,0.231868,0.608435,0,0.192599,0.062361,0.000099,20,2048,smooth_tchebycheff,1,0.064093,0.016039,200000,dazzling-sweep-24
77,problem_5e,342271.693519,0.753776,0.234615,0.781541,0,0.192599,0.062361,0.000099,20,2048,smooth_tchebycheff,2,0.064093,0.016039,200000,dazzling-sweep-24
78,problem_5e,267530.002666,0.589174,0.412088,0.920714,0,0.192599,0.062361,0.000099,20,2048,smooth_tchebycheff,3,0.064093,0.016039,200000,dazzling-sweep-24
79,problem_5e,345272.033984,0.760383,0.342857,0.767682,0,0.192599,0.062361,0.000099,20,2048,smooth_tchebycheff,4,0.064093,0.016039,200000,dazzling-sweep-24

In [6]:
envelope = pd.read_csv(envelope_file)
envelope

,problem,config,checkpoint,hypervolume,normalized_hv,percent_non_dominated,ordering_score,pref_grid_step,lr,gamma,batch_size,seed,timestamp
0,problem_1a,problem_1a.yml,NaN,138.553110,0.653088,0.428571,0.952267,0.05,0.0001,0.95,32,0,2026-05-01T17:57:14
1,problem_1a,problem_1a.yml,NaN,95.294066,0.449181,0.190476,0.920447,0.05,0.0001,0.95,32,1,2026-05-01T19:31:31
2,problem_0,problem_0.yml,NaN,402.162143,0.897233,0.190476,0.901369,0.05,0.0003,0.95,128,2,2026-05-01T20:59:01
3,problem_0,problem_0.yml,NaN,402.158129,0.897224,0.238095,0.901190,0.05,0.0003,0.95,128,1,2026-05-01T20:59:53
4,problem_0,problem_0.yml,NaN,429.772955,0.958833,0.333333,0.948840,0.05,0.0003,0.95,128,0,2026-05-01T20:59:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,problem_5e,problem_5e.yml,NaN,284696.740717,0.626980,0.204404,0.824449,0.05,0.0003,0.95,128,0,2026-05-04T09:06:17
76,problem_5e,problem_5e.yml,NaN,202019.103647,0.444901,0.108978,0.714117,0.05,0.0003,0.95,128,1,2026-05-04T09:52:57
77,problem_5e,problem_5e.yml,NaN,271328.477644,0.597540,0.131846,0.719119,0.05,0.0003,0.95,128,3,2026-05-04T09:56:51
78,problem_5e,problem_5e.yml,NaN,222580.795251,0.490184,0.059477,0.739113,0.05,0.0003,0.95,128,2,2026-05-04T09:59:27
79,problem_5e,problem_5e.yml,NaN,321740.508439,0.708561,0.244777,0.745449,0.05,0.0003,0.95,128,4,2026-05-04T10:16:42

In [7]:
def to_plot_df(
        df, 
        problem_col = 'problem', 
        metric_map = {
            'normalized_hv': 'HV Ratio',
            'percent_non_dominated': '% Non-Dominated',
            'ordering_score': 'Ordering Score',
        },
        run_idx = 'seed',
):
    """Extract, tidy, and pretify names."""
    plot_df = ( 
        df[[problem_col] + [k for k in metric_map.keys()] + [run_idx]]
        .set_index([problem_col, run_idx])
        .rename_axis('metric',axis=1)
        .stack()
    ).rename('score').reset_index()
    plot_df['metric'] = pd.Categorical(
        values=plot_df['metric'].map(metric_map),
        categories=[v for _,v in metric_map.items()],
        ordered=True
    )
    plot_df.rename(columns={problem_col:'Problem'}, inplace=True)
    plot_df['Problem'] = plot_df['Problem'].map({n:n.split('_')[1] for n in plot_df['Problem'].unique()})
    return plot_df

In [8]:
pdmorl_plot = to_plot_df(pdmorl)
display(pdmorl_plot.head(3))
pdmorl_plot.groupby(by='metric', observed=True)['score'].describe()

  Problem  seed           metric     score
0       0     1         HV Ratio  0.928839
1       0     1  % Non-Dominated  0.615385
2       0     1   Ordering Score  0.984510

,count,mean,std,min,25%,50%,75%,max
metric,,,,,,,,
HV Ratio,80.0,0.505065,0.298704,0.000046,0.263706,0.532617,0.655142,0.992326
% Non-Dominated,80.0,0.356641,0.386161,0.000549,0.050137,0.152747,0.692308,1.000000
Ordering Score,80.0,0.812106,0.153856,0.391170,0.691328,0.802321,0.978549,1.000000

In [9]:
pcpl_plot = to_plot_df(
    pcpl,
    problem_col='env_name',
    metric_map = {
        'normalized_hv': 'HV Ratio',
        'non_dominated': '% Non-Dominated',
        'ordering': 'Ordering Score',
    },    
    run_idx = 'seed',
)

In [10]:
envelope_plot = to_plot_df(envelope)
display(envelope_plot.head(3))
envelope_plot.groupby(by='metric', observed=True)['score'].describe()

  Problem  seed           metric     score
0      1a     0         HV Ratio  0.653088
1      1a     0  % Non-Dominated  0.428571
2      1a     0   Ordering Score  0.952267

,count,mean,std,min,25%,50%,75%,max
metric,,,,,,,,
HV Ratio,80.0,0.422828,0.269640,0.007536,0.169950,0.427486,0.604289,0.958833
% Non-Dominated,80.0,0.243390,0.294092,0.000188,0.032397,0.102249,0.392857,1.000000
Ordering Score,80.0,0.756898,0.166022,0.358696,0.622377,0.766633,0.901235,0.991273

In [11]:
display(pcpl_plot.head(3))
pcpl_plot.groupby(by=['metric'], observed=True)['score'].describe()

  Problem  seed           metric     score
0       0     1         HV Ratio  0.983708
1       0     1  % Non-Dominated  1.000000
2       0     1   Ordering Score  1.000000

,count,mean,std,min,25%,50%,75%,max
metric,,,,,,,,
HV Ratio,80.0,0.717013,0.232639,0.064898,0.587900,0.741135,0.892740,1.0
% Non-Dominated,80.0,0.453420,0.364621,0.001099,0.148352,0.307692,0.770055,1.0
Ordering Score,80.0,0.911822,0.107917,0.545746,0.877789,0.951027,0.986667,1.0

In [12]:
plot_df = pd.concat([
    pdmorl_plot.assign(Architecture='PD-MORL'),
    pcpl_plot.assign(Architecture='PCPL-PPO'),
    envelope_plot.assign(Architecture='Envelope'),
], ignore_index=True)
plot_df['Architecture'] = pd.Categorical(
    plot_df['Architecture'],
    categories=['PCPL-PPO', 'PD-MORL', 'Envelope'],
    ordered=True,
)
plot_df['Subproblem'] = plot_df['Problem'].apply(lambda s: s[1:])
plot_df['Problem Set'] = plot_df['Problem'].apply(lambda s: s[0])

_problem_order = sorted(plot_df['Problem'].unique())
plot_df['x_pos'] = plot_df['Problem'].map({p: i+1 for i, p in enumerate(_problem_order)})
_sep_xintercepts = [1.5, 4.5, 7.5, 9.5, 11.5]
_x_breaks = list(range(1, len(_problem_order) + 1))
plot_df

,Problem,seed,metric,score,Architecture,Subproblem,Problem Set,x_pos
0,0,1,HV Ratio,0.928839,PD-MORL,,0,1
1,0,1,% Non-Dominated,0.615385,PD-MORL,,0,1
2,0,1,Ordering Score,0.984510,PD-MORL,,0,1
3,0,2,HV Ratio,0.992326,PD-MORL,,0,1
4,0,2,% Non-Dominated,1.000000,PD-MORL,,0,1
...,...,...,...,...,...,...,...,...
715,5e,2,% Non-Dominated,0.059477,Envelope,e,5,16
716,5e,2,Ordering Score,0.739113,Envelope,e,5,16
717,5e,4,HV Ratio,0.708561,Envelope,e,5,16
718,5e,4,% Non-Dominated,0.244777,Envelope,e,5,16
719,5e,4,Ordering Score,0.745449,Envelope,e,5,16

In [ ]:
p = (
    p9.ggplot(data=plot_df, mapping=p9.aes(x='x_pos', y='score', fill='Architecture', color='Architecture'))
    + p9.facet_grid('metric~.')
    + p9.geom_vline(xintercept=_sep_xintercepts, color='lightgray', size=0.5)
    + p9.geom_point(
        position=p9.position_dodge(width=0.7),
        color='none',
        alpha=0.3,
        size=1.0,
    )
    + p9.stat_summary(
        geom='point',
        fun_y=np.mean,
        size=3,
        shape='_',
        stroke=1,
    )
    + p9.scale_x_continuous(breaks=_x_breaks, labels=_problem_order)
    + p9.theme_classic()
    + p9.theme(
        figure_size=(6.5,4.5),
        panel_grid_major_y=p9.element_line(color='lightgray', alpha=0.5),
        legend_direction='horizontal',
        legend_position='top',
        legend_box_margin=0,
        legend_box_spacing=0,
        strip_background=p9.element_blank(),
    )
    + p9.scale_color_brewer(type='qual', palette=2)
    + p9.scale_fill_brewer(type='qual', palette=2)
    + p9.xlab('Problem')
    + p9.ylab('Score')
)

p.save(f'{PLOT_DIR}/problems1-5_v3.pdf')
display(p)

In [ ]:
p = (
    p9.ggplot(data=plot_df, mapping=p9.aes(x='x_pos', y='score', fill='Architecture', color='Architecture'))
    + p9.facet_grid('metric~.')
    + p9.geom_vline(xintercept=_sep_xintercepts, color='lightgray', size=0.5)
    + p9.geom_point(
        position=p9.position_dodge(width=0.7),
        color='none',
        alpha=0.3,
        size=1.0,
    )
    + p9.stat_summary(
        geom='point',
        fun_y=np.mean,
        size=1.0,
        shape='d',
        stroke=1,
    )
    + p9.scale_x_continuous(breaks=_x_breaks, labels=_problem_order)
    + p9.theme_classic()
    + p9.theme(
        figure_size=(6.5,4.5),
        panel_grid_major_y=p9.element_line(color='lightgray', alpha=0.5),
        legend_direction='horizontal',
        legend_position='top',
        legend_box_margin=0,
        legend_box_spacing=0,
        strip_background=p9.element_blank(),
    )
    + p9.scale_color_brewer(type='qual', palette=2)
    + p9.scale_fill_brewer(type='qual', palette=2)
    + p9.xlab('Problem')
    + p9.ylab('Score')
)
p.save(f'{PLOT_DIR}/problems1-5_v4.pdf')
display(p)